CREATE TABLE Store(
	store_id NUMBER NOT NULL PRIMARY KEY,
	store_name VARCHAR2(30)
);

INSERT INTO Store VALUES(11, 'Walmart');
INSERT INTO Store VALUES(12, 'K-Mart');
INSERT INTO Store VALUES(13, 'BestBuy');
INSERT INTO Store VALUES(14, 'Newegg');
INSERT INTO Store VALUES(15, 'PC Richards');
INSERT INTO Store VALUES(16, 'Target');
INSERT INTO Store VALUES(17, 'Macy''s');
INSERT INTO Store VALUES(18, 'Target');
INSERT INTO Store VALUES(19, 'JCPenny');
INSERT INTO Store VALUES(20, 'Amazon');
